@startuml
actor ":Client" as Client
participant ":API Gateway\nKong" as Gateway
participant ":Portfolio Service" as Portfolio
database ":PostgreSQL\nbrokerx_portfolio" as DB
participant ":Kafka" as Kafka

Client -> Gateway : POST /api/v1/deposits (JWT)
Gateway -> Portfolio : Route /deposits
Portfolio -> DB : Tx idempotency ?\nWallet by accountId
DB --> Portfolio : OK / existing
Portfolio -> DB : Insert Tx (PENDING)\nUpdate wallet (+amount)\nUpdate Tx (SETTLED)
Portfolio -> Kafka : Publish "deposit.validated"\n{depositId, accountId, amount, balance}
Kafka --> Kafka : (disponible pour\norders/notifications)
Portfolio --> Gateway : 200 OK (newBalance, txId)
Gateway --> Client : 200 OK
@enduml
